services:
  hearsay:
    build: ./bot
    image: hearsay-bot
    volumes:
      - ./bot/data:/app/data
    command: ./hearsay -s 192.168.10.137:6697 -c \#test
    init: true
    restart: unless-stopped # change in production to `unless-stopped`
    depends_on:
      - api
    networks:
      - hearsay-net

  api:
    build: ./api
    image: hearsay-api
    command: sh -c "PYTHONPATH=./app_python uvicorn app_python.main:app --host 0.0.0.0 --port 8111 --workers 2"
    #ports:
    #  - "8111:8111"
    volumes:
      - ./bot/data:/app/data
    restart: no
    networks:
      - hearsay-net

networks:
  hearsay-net: