services:
  hearsay:
    build: ./bot
    image: hearsay-bot
    volumes:
      - hearsay-data:/app/data
    command: ./hearsay -s 192.168.10.137:6697 -c \#test
    restart: no # change in production to `unless-stopped`
    networks:
      - hearsay-net

  api:
    build: ./api
    image: hearsay-api
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8080:8080"
    volumes:
      - hearsay-data:/app/data
    restart: no
    networks:
      - hearsay-net
  
volumes:
  hearsay-data:

networks:
  hearsay-net: