services:
  hearsay:
    build: ./bot
    image: hearsay-bot
    volumes:
      - hearsay-data:/app/data
    restart: no # change in production to `unless-stopped`
    networks:
      - hearsay-net

  api:
    build: ./api
    image: hearsay-api
    ports:
      - "8080:8080"
    volumes:
      - hearsay-data:/app/data
    restart: no
    networks:
      - hearsay-net
  
volumes:
  hearsay-data:

networks:
  - hearsay-net